SELECT
    j.JOB_TITLE Cargo,
    ROUND(AVG(e.SALARY), 2) 'Média salarial',
    CASE
        WHEN ROUND(AVG(e.SALARY), 2) BETWEEN 2000 AND 5800 THEN 'Júnior'
        WHEN ROUND(AVG(e.SALARY), 2) BETWEEN 5801 AND 7500 THEN 'Pleno'
        WHEN ROUND(AVG(e.SALARY), 2) BETWEEN 7501 AND 10500 THEN 'Sênior'
        ELSE 'CEO'
    END AS Senioridade
FROM
    jobs j
        INNER JOIN
    employees e ON j.JOB_ID = e.JOB_ID
GROUP BY JOB_TITLE
ORDER BY ROUND(AVG(e.SALARY), 2) , JOB_TITLE;
